// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Vivaldi",
  handlers: [
    {
      match: /^https?:\/\/app\.bitrise\.com\/.*$/,
      browser: "Safari"
    },
    {
      match: /^https?:\/\/console\.firebase\.google\.com\/.*$/,
      browser: "Safari"
    }
  ]
}