tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "arp-scan"
brew "cloc"
brew "cmake"
brew "colordiff"
brew "curl"
brew "lame"
brew "goenv"
brew "gnu-sed"
brew "jq"
brew "java"
brew "mas"
brew "mint"
brew "nodebrew"
brew "pyenv"
brew "rbenv"
brew "rbenv-communal-gems"
brew "tcptraceroute"
brew "tfenv"
brew "tmux"
brew "translate-shell"
brew "wget"
brew "zplug"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alfred", args: { appdir: "/Applications" }
cask "android-studio", args: { appdir: "/Applications" }
cask "appcleaner", args: { appdir: "/Applications" }
cask "balenaetcher"
cask "bettertouchtool"
cask "cheatsheet", args: { appdir: "/Applications" }
cask "dash", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "finicky"
cask "firefox", args: { appdir: "/Applications" }
cask "google-japanese-ime", args: { appdir: "/Applications" }
cask "handbrake", args: { appdir: "/Applications" }
cask "imageoptim", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "keyboardcleantool", args: { appdir: "/Applications" }
cask "menumeters", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "provisionql", args: { appdir: "/Applications" }
cask "sdformatter"
cask "sf-symbols", args: { appdir: "/Applications" }
cask "shiftit", args: { appdir: "/Applications" }
cask "sketch"
cask "sourcetree", args: { appdir: "/Applications" }
cask "svnx", args: { appdir: "/Applications" }
cask "the-unarchiver", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "vivaldi"
cask "vlc", args: { appdir: "/Applications" }
cask "wkhtmltopdf"
cask "zeplin", args: { appdir: "/Applications" }
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
